[build]
  base = "backend"
  command = "npm install && cd ../frontend && npm install && npm run build"
  publish = "../frontend/dist" 

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/:splat"
  status = 200
  force = true